# Generated by Django 2.1.1 on 2018-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180906_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(blank=True, help_text='html contents', verbose_name='컨텐츠'),
        ),
    ]
