# Generated by Django 2.1.1 on 2018-09-15 16:31

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180907_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=martor.models.MartorField(blank=True, help_text='html contents', verbose_name='컨텐츠'),
        ),
    ]
